Repository EpicGamesExt/PixelStreamingInfrastructure, pull requests merged in 2024-07, with the labels that each got.

#167 Frontend - Provide default values to avoid potential NAN value returned when using dynamic player aspect ratios
  Frontend/library/src/Util/CoordinateConverter.ts
Labels: auto-backport, auto-backport-to-UE5.4, auto-backport-to-UE5.3, auto-backport-to-UE5.2

#197 Disconnect flow fixes
  Frontend/library/src/WebRtcPlayer/WebRtcPlayerController.ts
  Frontend/ui-library/src/Application/Application.ts
Labels: auto-backport, auto-backport-to-UE5.4, auto-backport-to-UE5.3, auto-backport-to-UE5.2, auto-backport-to-UE5.5

#204 Added fuzzy matching to preferred codecs so Firefox can connect to VPX streams
  Frontend/library/src/PeerConnectionController/PeerConnectionController.ts
Labels: bug, auto-backport, auto-backport-to-UE5.4, auto-backport-to-UE5.3, auto-backport-to-UE5.2, auto-backport-to-UE5.5

#213 Fix: Mobile UI not scaling correctly when nav bars are present.
  Frontend/implementations/typescript/src/player.html
Labels: bug, auto-backport, auto-backport-to-UE5.4, auto-backport-to-UE5.3, auto-backport-to-UE5.2, auto-backport-to-UE5.5
