Repository EpicGamesExt/PixelStreamingInfrastructure, pull requests merged in 2024-12, with the labels that each got.

#358 Fix: Unnecessary warnings about unregistered message handlers
  Frontend/library/src/WebRtcPlayer/WebRtcPlayerController.ts
Labels: bug, auto-backport, auto-backport-to-UE5.5

#356 Add: Preferred quality option (and UI) for simulcast or svc enabled streams
  Common/protobuf/signalling_messages.proto
  Common/src/Messages/signalling_messages.ts
  Frontend/Docs/Settings Panel.md
  Frontend/library/src/Config/Config.ts
  Frontend/library/src/WebRtcPlayer/WebRtcPlayerController.ts
  Frontend/library/src/pixelstreamingfrontend.ts
  Frontend/ui-library/src/Application/Application.ts
  Frontend/ui-library/src/Config/ConfigUI.ts
  Frontend/ui-library/src/Config/SettingUIFlag.ts
  Frontend/ui-library/src/Config/SettingUINumber.ts
  Frontend/ui-library/src/Config/SettingUIText.ts
  SFU/sfu_server.js
  Signalling/src/PlayerConnection.ts
Labels: enhancement, auto-backport, auto-backport-to-UE5.5

#355 Enabled a few more ts compiler options
  Common/package.json
  Common/tsconfig.base.json
  Common/tsconfig.esm.json
  Extras/FrontendTests/tests/extras.ts
  Extras/FrontendTests/tests/keyboard.spec.ts
  Extras/FrontendTests/tests/matchers.ts
  Extras/FrontendTests/tests/mouse.spec.ts
  Extras/FrontendTests/tests/resolution_changes.spec.ts
  Extras/JSStreamer/package.json
  Frontend/implementations/typescript/package.json
  Frontend/library/package.json
  Frontend/library/src/Config/SettingFlag.ts
  Frontend/library/src/Config/SettingNumber.ts
  Frontend/library/src/Config/SettingOption.ts
  Frontend/library/src/Config/SettingText.ts
  Frontend/library/src/DataChannel/DataChannelController.ts
  Frontend/library/src/Inputs/MouseControllerHovering.ts
  Frontend/library/src/Inputs/MouseControllerLocked.ts
  Frontend/library/src/PeerConnectionController/PeerConnectionController.ts
  Frontend/library/src/UeInstanceMessage/SendMessageController.ts
  Frontend/library/src/Util/EventEmitter.ts
  Frontend/library/src/VideoPlayer/VideoPlayer.ts
  Frontend/library/src/__test__/mockRTCRtpReceiver.ts
  Frontend/library/src/__test__/mockWebSocket.ts
  Frontend/library/tsconfig.esm.json
  Frontend/library/tsconfig.json
  Frontend/ui-library/.eslintrc.js
  Frontend/ui-library/package.json
  Frontend/ui-library/src/Config/SettingUIFlag.ts
  Frontend/ui-library/src/Config/SettingUINumber.ts
  Frontend/ui-library/src/Config/SettingUIOption.ts
  Frontend/ui-library/src/Config/SettingUIText.ts
  Frontend/ui-library/src/UI/FullscreenIcon.ts
  Frontend/ui-library/tsconfig.esm.json
  Frontend/ui-library/tsconfig.json
  Signalling/package.json
  Signalling/src/Logger.ts
  Signalling/src/SignallingServer.ts
  Signalling/tsconfig.base.json
  package-lock.json
Labels: auto-backport, auto-backport-to-UE5.5

#368 Cleaning up frontend library exports
  Frontend/library/src/pixelstreamingfrontend.ts
Labels: auto-backport, auto-backport-to-UE5.4, auto-backport-to-UE5.3, auto-backport-to-UE5.5

#372 Add: Functionality to disable setting UI on a per setting basis
  Frontend/ui-library/src/Application/Application.ts
  Frontend/ui-library/src/Config/ConfigUI.ts
  Frontend/ui-library/src/UI/UIConfigurationTypes.ts
Labels: auto-backport, auto-backport-to-UE5.5

#377 Add: Functionality to disable UI on a per section basis
  Frontend/ui-library/src/Application/Application.ts
  Frontend/ui-library/src/Config/ConfigUI.ts
  Frontend/ui-library/src/UI/DataChannelLatencyTest.ts
  Frontend/ui-library/src/UI/LatencyTest.ts
  Frontend/ui-library/src/UI/StatsPanel.ts
  Frontend/ui-library/src/UI/UIConfigurationTypes.ts
Labels: auto-backport, auto-backport-to-UE5.5

#380 Fix: Handle the case where the first connected gamepad isn't index 0
  Frontend/library/src/Inputs/GamepadController.ts
Labels: auto-backport, auto-backport-to-UE5.4, auto-backport-to-UE5.3, auto-backport-to-UE5.5

#383 Fix bad id checks
  Frontend/library/src/Inputs/GamepadController.ts
Labels: auto-backport, auto-backport-to-UE5.5
