Repository EpicGamesExt/PixelStreamingInfrastructure, pull requests merged in 2024-11, with the labels that each got.

#309 Fix: SFU not being able reconnect once a streamer has disconnected
  SFU/sfu_server.js
Labels: auto-backport, auto-backport-to-UE5.4, auto-backport-to-UE5.3

#314 Remove redundant and rigid setting of signaling url in uiless.html
  Frontend/implementations/typescript/src/uiless.ts
Labels: auto-backport, auto-backport-to-UE5.4, auto-backport-to-UE5.3, auto-backport-to-UE5.2, auto-backport-to-UE5.5

#323 fix: change typo in unregister callbacks to remove event listeners
  Frontend/library/src/Inputs/TouchController.ts
Labels: auto-backport, auto-backport-to-UE5.5

#327 Add 5.5 changelist to CHANGELOG.md
  CHANGELOG.md
Labels: auto-backport, auto-backport-to-UE5.5

#334 Remove fullscreen button on iPad if using a non Safari browser
  Frontend/implementations/typescript/src/player.html
  Frontend/ui-library/src/Application/Application.ts
Labels: auto-backport, auto-backport-to-UE5.4, auto-backport-to-UE5.3, auto-backport-to-UE5.2
