Repository EpicGamesExt/PixelStreamingInfrastructure, pull requests merged in 2025-05, with the labels that each got.

#604 Fixing path issues in platform_scripts
  .github/workflows/healthcheck-platform-scripts.yml
  SignallingWebServer/platform_scripts/bash/common.sh
Labels: auto-backport, auto-backport-to-UE5.5

#607 Better handling of node in Linux scripts.
  .backportrc.json
  SignallingWebServer/platform_scripts/bash/common.sh
Labels: auto-backport, auto-backport-to-UE5.5, auto-backport-to-LatencyTest

#611 Fixing a small issue with how path was setup previously.
  SignallingWebServer/platform_scripts/bash/common.sh
Labels: auto-backport, auto-backport-to-UE5.5, auto-backport-to-LatencyTest

#623 fix: Adding small delay in publish actions.
  .github/workflows/changesets-publish-npm-packages.yml
Labels: auto-backport, auto-backport-to-UE5.5, auto-backport-to-UE5.6

#618 Fixing windows SFU platform scripts.
  SFU/platform_scripts/cmd/setup_node.bat
Labels: auto-backport, auto-backport-to-UE5.5, auto-backport-to-UE5.6

#614 feat: reverse proxy configuration
  .changeset/red-turtles-cross.md
  SignallingWebServer/config.json
  SignallingWebServer/src/index.ts
Labels: auto-backport, auto-backport-to-UE5.5, auto-backport-to-UE5.6

#632 chore: Fixing readme badges for 5.5
  README.md
Labels: auto-backport, auto-backport-to-UE5.6

#636 Removing some extras stuff.
  Extras/mediasoup-sdp-bridge/tools/browser-rtpcapabilities/package-lock.json
  Extras/mediasoup-sdp-bridge/tools/browser-rtpcapabilities/package.json
  Extras/mediasoup-sdp-bridge/tools/browser-rtpcapabilities/src/client/index.html
  Extras/mediasoup-sdp-bridge/tools/browser-rtpcapabilities/src/client/index.js
Labels: auto-backport, auto-backport-to-UE5.5, auto-backport-to-UE5.6

#639 Updating http-proxy-middleware
  Extras/JSStreamer/package.json
  package-lock.json
Labels: auto-backport, auto-backport-to-UE5.5, auto-backport-to-UE5.6

#642 Explicitly adding permissions to all workflows.
  .github/workflows/backport.yml
  .github/workflows/changesets-publish-npm-packages.yml
  .github/workflows/healthcheck-frontend.yml
  .github/workflows/healthcheck-image-sfu.yml
  .github/workflows/healthcheck-image-wilbur.yml
  .github/workflows/healthcheck-libraries.yml
  .github/workflows/healthcheck-libs-with-public-deps.yml
  .github/workflows/healthcheck-markdown-links.yml
  .github/workflows/healthcheck-platform-scripts.yml
  .github/workflows/healthcheck-signalling-protocol.yml
  .github/workflows/healthcheck-streaming.yml
  .github/workflows/publish-sfu-image.yml
  .github/workflows/stale.yml
Labels: auto-backport, auto-backport-to-UE5.6

#644 Backport action needs contents write.
  .github/workflows/backport.yml
Labels: auto-backport, auto-backport-to-UE5.6

#647 Feature: Dump latency stats to CSV | Re-ship: 4.27 browser send offer support
  .backportrc.json
  .changeset/weak-files-wait.md
  Frontend/library/src/Config/Config.ts
  Frontend/library/src/PeerConnectionController/AggregatedStats.ts
  Frontend/library/src/WebRtcPlayer/WebRtcPlayerController.ts
  Frontend/ui-library/src/Application/Application.ts
  Frontend/ui-library/src/Config/ConfigUI.ts
  Frontend/ui-library/src/UI/SessionTest.ts
  Frontend/ui-library/src/UI/StatsPanel.ts
  Frontend/ui-library/src/UI/UIConfigurationTypes.ts
Labels: auto-backport, auto-backport-to-UE5.6

#656 Updating formatting of changesets.
  .changeset/sweet-foxes-remain.md
  .changeset/weak-files-wait.md
Labels: auto-backport, auto-backport-to-UE5.6
