Repository EpicGamesExt/PixelStreamingInfrastructure, pull requests merged in 2025-01, with the labels that each got.

#392 Update copyright/license year to 2025
  CONTRIBUTING.md
  Docs/README.md
  Frontend/Docs/Settings Panel.md
  Frontend/README.md
  LICENSE.md
Labels: auto-backport, auto-backport-to-UE5.4, auto-backport-to-UE5.3, auto-backport-to-UE5.2, auto-backport-to-UE5.5

#410 Fix: Chrome + iPad not creating rootElement early enough for custom frontends
  Frontend/ui-library/src/Application/Application.ts
Labels: bug, auto-backport, auto-backport-to-UE5.4, auto-backport-to-UE5.3, auto-backport-to-UE5.5

#409 Adding a heartbeat to the signalling protocol.
  Common/src/Protocol/KeepaliveMonitor.ts
  Common/src/Protocol/SignallingProtocol.ts
  Common/src/Transport/WebSocketTransport.ts
  Common/src/pixelstreamingcommon.ts
  Extras/JSStreamer/src/streamer.ts
  Frontend/library/src/Config/Config.ts
  Frontend/library/src/WebRtcPlayer/WebRtcPlayerController.ts
  Frontend/ui-library/src/Config/ConfigUI.ts
  Signalling/src/PlayerConnection.ts
  Signalling/src/SFUConnection.ts
  Signalling/src/StreamerConnection.ts
Labels: auto-backport, auto-backport-to-UE5.5
